### ISSUE TITLE
Malformed version number string undefined

### ISSUE THREAD

**Issue by oliviadodge** [sparkfabrik/android-build-action#15]
Getting the following:

```
/usr/lib/ruby/vendor_ruby/rubygems/version.rb:216:in `initialize': Malformed version number string undefined (ArgumentError)
	from /usr/lib/ruby/vendor_ruby/rubygems/version.rb:207:in `new'
	from /usr/lib/ruby/vendor_ruby/rubygems/version.rb:207:in `new'
	from /var/lib/gems/3.0.0/gems/fastlane-2.211.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:29:in `block in show_update_status'
	from /var/lib/gems/3.0.0/gems/fastlane-2.211.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `each'
	from /var/lib/gems/3.0.0/gems/fastlane-2.211.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `show_update_status'
	from /var/lib/gems/3.0.0/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:45:in `ensure in start'
	from /var/lib/gems/3.0.0/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:55:in `start'
	from /var/lib/gems/3.0.0/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /var/lib/gems/3.0.0/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:25:in `load'
	from /usr/local/bin/fastlane:25:in `<main>'
```

My script:

`    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.2.0
      with:
        project-path: .
        output-path: MyApp.apk`

**Comment by EmilianoMorghen** [comment]
Hi @oliviadodge, we just released a [new version](https://github.com/sparkfabrik/android-build-action/releases/tag/v1.3.0) that should fix the problem, could you try it?
